cache:
  paths:
    - .npm/ # для хранения зависимостей сборки фронтенда

stages:
  - build
  - test
  - notify
  - release

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}-RELEASE

build-frontend-code-job:
  stage: build
  only:
    changes:
      - frontend/**/*
  script:
    - cd frontend
    - npm install
    - npm run build
    - echo $CI_JOB_URL'/artifacts/download' > url.txt
  artifacts:
    expire_in: 12 hrs
    paths:
      - frontend/dist/frontend/
      - frontend/url.txt

telegram-notification-frontend:
  stage: notify
  only:
    changes:
      - frontend/**/*
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - cd frontend
    - export LINK_TO_DW_ARTIFACT=$(cat url.txt)
    # Тут нужно спрятать chat_id и bot_id в переменные, но это не вышло, запутался в одинарных кавычках,
    # двойных кавычках, в скалярах. Не понимаю что за конструкция >- не смог её загуглить.
    - >-
      curl -X POST -H "Content-Type: application/json" -d '{"chat_id": "-XXXXXXXX", "text": "Artemiy Zhuravlev has built frontend download link: '$LINK_TO_DW_ARTIFACT'", "disable_notification": true}' https://api.telegram.org/botXXXXXXXX:XXXXXXXX/sendMessage
  needs:
    - build-frontend-code-job

sonarqube-frontend-sast:
  image: sonarsource/sonar-scanner-cli:latest
  stage: test
  needs:
    - build-frontend-code-job
  dependencies:
    - build-frontend-code-job
  script:
    - cd frontend
    - >
      sonar-scanner 
      -Dsonar.projectKey="${SONAR_PROJECT_KEY}"_frontend 
      -Dsonar.sources=. 
      -Dsonar.host.url="${SONARQUBE_URL}" 
      -Dsonar.login="${SONAR_PROJECT_KEY_FRONT}"

# Спринт6. Добавляем отправку артифактов на nexus
upload-frontend-release:
  stage: release
  only:
    changes:
      - frontend/**/*
  needs:
    - build-frontend-code-job
  script:
    - cd frontend/dist
    - tar czvf sausage-store-${VERSION}.tar.gz frontend
    - >
      curl -v -u "${NEXUS_REPO_USER}:${NEXUS_REPO_PASS}" 
      --upload-file sausage-store-${VERSION}.tar.gz 
      ${NEXUS_REPO_URL}/${NEXUS_REPO_FRONTEND_NAME}/sausage-store-${VERSION}.tar.gz
